apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-srv-deployment
  labels:
    app: chat-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-srv
  template:
    metadata:
      labels:
        app: chat-srv
    spec:
      containers:
        - name: chat-srv
          image: muhammedajmal/skyway-chat-srv:11
---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv-service
spec:
  # type: NodePort
  selector:
    app: chat-srv
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
