apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-skyway-host
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "ajmal.com"
      http:
        paths:
          - pathType: Prefix
            path: "/api/user-srv/"
            backend:
              service:
                name: user-srv-service
                port:
                  number: 3000
          # - pathType: Prefix
          #   path: "/api/venture-srv"
          #   backend:
          #     service:
          #       name: venture-srv-service
          #       port:
          #         number: 3001
          - path: /api/admin-srv/
            pathType: Prefix
            backend:
              service:
                name: admin-srv-service
                port:
                  number: 3002
          - path: /api/chat-srv/
            pathType: Prefix
            backend:
              service:
                name: chat-srv-service
                port:
                  number: 4003
          # - pathType: Prefix
          #   path: "/"
          #   backend:
          #     service:
          #       name: client-srv-service
          #       port:
          #         number: 5173
  # ingressClassName: 
