apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-skyway-host
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "ajmal.com"
      http:
        paths:
          - pathType: Prefix
            path: "/api/user-srv"
            backend:
              service:
                name: user-srv-service
                port:
                  number: 3000
